default['htmlentities']['install_path'] = "/etc/xml"
default['htmlentities']['baseurl'] = "http://www.w3.org/TR/xhtml1/DTD/"
default['htmlentities']['latin1_filename'] = "xhtml-lat1.ent"
default['htmlentities']['special_filename'] = "xhtml-special.ent"
default['htmlentities']['symbol_filename'] = "xhtml-symbol.ent"